CREATE TABLE IF NOT EXISTS scene_libraries (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  drama_id INTEGER,
  location VARCHAR(255) NOT NULL DEFAULT '',
  time VARCHAR(255),
  prompt TEXT,
  description VARCHAR(2000),
  image_url VARCHAR(500),
  local_path VARCHAR(500),
  category VARCHAR(255),
  tags VARCHAR(255),
  source_type VARCHAR(255),
  source_id VARCHAR(36),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

CREATE TABLE IF NOT EXISTS prop_libraries (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  drama_id INTEGER,
  name VARCHAR(255) NOT NULL DEFAULT '',
  description VARCHAR(2000),
  prompt TEXT,
  image_url VARCHAR(500),
  local_path VARCHAR(500),
  category VARCHAR(255),
  tags VARCHAR(255),
  source_type VARCHAR(255),
  source_id VARCHAR(36),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);