CREATE TABLE IF NOT EXISTS image_proxy_cache (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  cache_key VARCHAR(64) NOT NULL UNIQUE,
  proxy_url VARCHAR(500) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);