ALTER TABLE storyboards ADD COLUMN segment_index INTEGER DEFAULT 0;
ALTER TABLE storyboards ADD COLUMN segment_title VARCHAR(255);

CREATE TABLE IF NOT EXISTS ai_model_map (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL UNIQUE,
  service_type VARCHAR(255) NOT NULL DEFAULT 'text',
  config_id INTEGER,
  model_override VARCHAR(255),
  description VARCHAR(2000),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);