CREATE TABLE IF NOT EXISTS enterprises (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  short_name VARCHAR(50),
  logo VARCHAR(255),
  domain VARCHAR(100),
  status TINYINT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  enterprise_id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  status TINYINT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  enterprise_id INTEGER NOT NULL,
  name VARCHAR(50) NOT NULL,
  code VARCHAR(50) NOT NULL,
  description VARCHAR(500),
  permissions TEXT,
  status TINYINT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

ALTER TABLE teams ADD CONSTRAINT IF NOT EXISTS fk_teams_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises(id) ON DELETE CASCADE;
ALTER TABLE roles ADD CONSTRAINT IF NOT EXISTS fk_roles_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises(id) ON DELETE CASCADE;

ALTER TABLE roles ADD UNIQUE KEY IF NOT EXISTS uk_enterprise_code (enterprise_id, code);

ALTER TABLE users ADD COLUMN IF NOT EXISTS enterprise_id INTEGER DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS team_id INTEGER DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS user_type VARCHAR(20) DEFAULT 'individual';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by INTEGER DEFAULT NULL;

ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS fk_users_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS fk_users_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS fk_users_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE dramas ADD COLUMN IF NOT EXISTS created_by INTEGER DEFAULT NULL;
ALTER TABLE dramas ADD COLUMN IF NOT EXISTS enterprise_id INTEGER DEFAULT NULL;
ALTER TABLE dramas ADD COLUMN IF NOT EXISTS team_id INTEGER DEFAULT NULL;

ALTER TABLE dramas ADD CONSTRAINT IF NOT EXISTS fk_dramas_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE dramas ADD CONSTRAINT IF NOT EXISTS fk_dramas_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises(id) ON DELETE SET NULL;
ALTER TABLE dramas ADD CONSTRAINT IF NOT EXISTS fk_dramas_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL;