CREATE TABLE IF NOT EXISTS user_settings (
  user_id BIGINT NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  value TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, `key`),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);